name: docs
on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      # - id: string
      #   uses: ASzc/change-string-case-action@v1
      #   with:
      #     string: ${{ github.event.repository.name }}
      - uses: actions/checkout@v2
      - name: print name
        # run: |
        #   echo ${{ github.event.repository.name }}
        #   name: downcase REPO
        run: |
          #export REPO=${{steps.string.outputs.lowercase}}
          #echo $REPO
          REPO_URL=$(git config --get remote.origin.url)
          REPO_NAME=$(basename -s .git $REPO_URL)
          REPO_NAME=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(dirname $REPO_URL | xargs basename)

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      # - name: Get pip cache dir
      #   id: pip-cache
      #   run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Install requirements
        run: |
          pip3 install sphinx-rtd-theme

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Add any new modules
        run: |
          # rm docs/${{ github.event.repository.name }}.rst
          # sphinx-apidoc -o docs ${{ github.event.repository.name }}
          rm docs/$REPO_NAME.rst
          sphinx-apidoc -o docs $REPO_NAME/

      - name: Build docs
        run: |
          cd docs
          make html

      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
